import { Activity, CheckCircle2, Clock3, Database, HardDrive, XCircle } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, PageHeader } from "../components/ui";
import { activity, chartData } from "../data/demo";

export default function UsagePage() {
  const stats = [["Total requests", "284,621", "+12.4%", Activity, "text-brand-600 bg-brand-50"], ["Successful", "279,412", "98.17%", CheckCircle2, "text-green-600 bg-green-50"], ["Failed", "5,209", "1.83%", XCircle, "text-red-600 bg-red-50"], ["P95 latency", "184 ms", "-16ms", Clock3, "text-amber-600 bg-amber-50"]];
  return <>
    <PageHeader eyebrow="Aurora Commerce" title="API usage" description="Monitor traffic, performance, errors, and resource consumption." actions={<select className="h-10 rounded-lg border border-line bg-white px-3 text-sm"><option>Last 7 days</option><option>Last 30 days</option></select>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, change, Icon, color]) => <Card key={label} className="p-5"><span className={`grid size-9 place-items-center rounded-lg ${color}`}><Icon className="size-4" /></span><p className="mt-4 text-2xl font-bold">{value}</p><div className="mt-1 flex items-center justify-between text-xs"><span className="text-muted">{label}</span><span className="font-semibold text-slate-600">{change}</span></div></Card>)}</div>
    <Card className="mt-5 p-5"><div><h2 className="font-bold">Requests and errors</h2><p className="mt-1 text-xs text-muted">Daily API activity over the selected period</p></div><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={(v) => `${v / 1000}k`}/><Tooltip/><Area type="monotone" dataKey="requests" stroke="#6c63ff" fill="#6c63ff22" strokeWidth={2.5}/><Area type="monotone" dataKey="errors" stroke="#dc2626" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Card><div className="border-b border-line p-5"><h2 className="font-bold">Recent requests</h2></div><div className="divide-y divide-line">{activity.map((item, index) => <div key={index} className="flex items-center gap-3 px-5 py-3.5"><span className="w-12 font-mono text-xs font-bold text-brand-600">{item.method}</span><code className="min-w-0 flex-1 truncate font-mono text-xs">{item.endpoint}</code><span className={item.status < 300 ? "text-xs text-green-600" : "text-xs text-red-600"}>{item.status}</span><span className="text-xs text-muted">{item.time}</span></div>)}</div></Card><Card className="p-5"><h2 className="font-bold">Resource usage</h2><div className="mt-6 space-y-6">{[[Database, "Database", "4.2 GB of 10 GB", "w-[42%]"], [HardDrive, "Storage", "6.8 GB of 10 GB", "w-[68%]"]].map(([Icon, label, text, width]) => <div key={label}><div className="flex items-center gap-2"><Icon className="size-4 text-brand-600" /><span className="text-sm font-semibold">{label}</span><span className="ml-auto text-xs text-muted">{text}</span></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full bg-brand-500 ${width}`} /></div></div>)}</div></Card></div>
  </>;
}
